#!/usr/bin/env python3
"""Generate the agent-facing support matrix from registry/capabilities.json.

Usage:
  python registry/build.py            # regenerate support-matrix.md
  python registry/build.py --check    # exit 1 if the matrix on disk is stale

Stdlib-only. Exit codes: 0 ok/up-to-date, 1 stale (--check), 2 registry error.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
REGISTRY = REPO_ROOT / "registry" / "capabilities.json"
MATRIX = REPO_ROOT / "skills" / "eodhd-api" / "references" / "general" / "support-matrix.md"

TIER_ORDER = ["validated", "fallback", "documented"]
TIER_BLURB = {
    "validated": "In the Python client **and** covered by a passing e2e test. Prefer these.",
    "fallback": "In the Python client but not e2e-verified (often subscription-gated). "
                "Works, but verify the response shape.",
    "documented": "Documented only — call via `curl` per the endpoint doc. Not in the Python client.",
}
BANNER = ("<!-- GENERATED by registry/build.py — do not edit by hand. "
          "Run `python registry/build.py`. -->")


def load_registry() -> list:
    try:
        data = json.loads(REGISTRY.read_text(encoding="utf-8"))
    except FileNotFoundError:
        print(f"Error: registry not found at {REGISTRY}", file=sys.stderr)
        raise SystemExit(2)
    except json.JSONDecodeError as exc:
        print(f"Error: invalid JSON in {REGISTRY}: {exc}", file=sys.stderr)
        raise SystemExit(2)
    if not isinstance(data, list):
        print("Error: registry must be a JSON array", file=sys.stderr)
        raise SystemExit(2)
    return data


def render(registry: list) -> str:
    lines = [
        BANNER,
        "",
        "# EODHD Endpoint Support Matrix",
        "",
        "Source of truth: `registry/capabilities.json`. "
        "Regenerate with `python registry/build.py`.",
        "",
        "## Support tiers",
        "",
    ]
    for tier in TIER_ORDER:
        lines.append(f"- **{tier}** — {TIER_BLURB[tier]}")
    lines.append("")
    for tier in TIER_ORDER:
        entries = sorted(
            [e for e in registry if e.get("support_tier") == tier],
            key=lambda e: e.get("id", ""),
        )
        lines.append(f"## {tier} ({len(entries)})")
        lines.append("")
        if not entries:
            lines.append("_None._")
            lines.append("")
            continue
        lines.append("| id | transport | path | response_family | doc |")
        lines.append("|---|---|---|---|---|")
        for e in entries:
            doc = e.get("doc_path", "")
            doc_link = f"[{Path(doc).name}](../../{doc})" if doc else ""
            lines.append(
                f"| `{e.get('id','')}` | {e.get('transport','')} | `{e.get('path','')}` "
                f"| {e.get('response_family','')} | {doc_link} |"
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    registry = load_registry()
    content = render(registry)
    if "--check" in sys.argv[1:]:
        existing = MATRIX.read_text(encoding="utf-8") if MATRIX.exists() else ""
        if existing != content:
            print(f"Error: {MATRIX.relative_to(REPO_ROOT)} is stale. "
                  f"Run: python registry/build.py", file=sys.stderr)
            return 1
        print("support-matrix.md is up to date")
        return 0
    MATRIX.parent.mkdir(parents=True, exist_ok=True)
    MATRIX.write_text(content, encoding="utf-8")
    print(f"Wrote {MATRIX.relative_to(REPO_ROOT)} ({len(registry)} endpoints)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
